build:
  goos:
    - windows
    - darwin
    - linux
  goarch:
    - amd64
    - arm
    - arm64
    - 386
    env:
      - CGO_ENABLED=0
    flags:
      - -mod=vendor

release:
  prerelease: auto

universal_binaries:
  - replace: true

brews
  - 
    name: locu
    homepage: https://github.com/LocuCode/LocuCLI
    tap:
      owner: locu
      name: homebrew-locu
    commit_author:
      name: anupsingh
      email: anup@locu.io

checksum:
  name_template: 'checksums.txt'