builds:
  - binary: locu
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    flags:
      - -mod=vendor

release:
  prerelease: auto

universal_binaries:
  - replace: true

brews:
  -
    name: locu
    homepage: https://github.com/LocuCode/LocuCLI
    tap:
      owner: anupsingh
      name: homebrew-locu
    commit_author:
      name: anup
      email: anup@locu.io

checksum:
  name_template: 'checksums.txt'